kind : Service
apiVersion: v1

metadata:
 name: mysql-service
 namespace: mysql-ns

spec:
 clusterIP: None
 selector:
  app: mysql
 ports:
 - name: mysql
   protocol: TCP
   targetPort: 3306
   port: 3306
